services:
  - type: web
    name: inmobiliaria-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn django_inmobiliaria.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_inmobiliaria.settings
      - key: PYTHON_VERSION
        value: 3.11
