# Generated by Django 5.2.4 on 2025-07-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('local_comercial', 'Local Comercial'), ('oficina', 'Oficina'), ('galpon', 'Galpón'), ('deposito', 'Depósito'), ('otro', 'Otro')], max_length=50)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], max_length=50)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('metros_cuadrados_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('metros_cuadrados_cubierta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('banios', models.IntegerField(blank=True, null=True)),
                ('cocheras', models.IntegerField(blank=True, null=True)),
                ('antiguedad', models.IntegerField(blank=True, help_text='Años de antigüedad', null=True)),
                ('amenidades', models.TextField(blank=True, help_text='Lista de amenidades separadas por comas')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='propiedades_imagenes/')),
                ('is_destacada', models.BooleanField(default=False)),
                ('estado_publicacion', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField()),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='web_app.propiedad')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades_galeria/')),
                ('descripcion_corta', models.CharField(blank=True, max_length=100)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='web_app.propiedad')),
            ],
        ),
    ]
