# Generated by Django 5.2.4 on 2025-07-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='acepta_mascotas',
            field=models.BooleanField(default=False, help_text='Marcar si la propiedad permite mascotas.', verbose_name='Acepta Mascotas (Pet-Friendly)'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_mascota_permitida',
            field=models.CharField(blank=True, choices=[('cualquiera', 'Cualquier tamaño'), ('pequena', 'Pequeña'), ('mediana', 'Mediana'), ('grande', 'Grande'), ('no_especificado', 'No especificado')], default='no_especificado', help_text='Si acepta mascotas, especificar el tamaño.', max_length=20, null=True, verbose_name='Tipo de Mascota Permitida'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='web_app_imagenes/'),
        ),
        migrations.AlterField(
            model_name='propiedadimagen',
            name='imagen',
            field=models.ImageField(upload_to='web_app_galeria/'),
        ),
    ]
