# Generated by Django 5.2.4 on 2025-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_propiedad_acepta_mascotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='acepta_mascotas',
            field=models.BooleanField(default=False, help_text='Marcar si la propiedad permite mascotas.', verbose_name='Acepta Mascotas'),
        ),
    ]
